# Конфигурационный файл демона

# Обязательный каталог, в котором нужно удалять все подпапки с содержимым
DIR1=/home/uvb/Workspace/daemon_lab/watch_folder

# Интервал между очистками (в секундах)
INTERVAL=20

